version: '3'
services:
  subha-springboot-container:
    image: subha-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/subha-springboot-container
    ports:
      - "8080-8100:8080"
